# Setup
title:  Shin-ichiro's homepage
description:  Bookmark this to keep an eye on my project updates!
baseurl:   ""
paginate:  1
local:  "ja"

# About/contact
author:  Shin-ichiro-I
name:  
url:  

# Gems
gems:
  -jekyll-paginate

# Others  
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# theme: jekyll-theme-cayman
