title: 放課後のサイエンス
description: MI、Science, Chemical Industry, Martial Arts, etc.

url: https://shin-ichiro-i.github.io/
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: "" # Ex: /project-page
paginate_path: "page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    # - title: Contact
    #   url: /contact

social:
    github: Shin-ichiro-I
    # twitter: brianmaierjr
    # facebook: brianmaierjr
    # email: brimaidesigns@gmail.com
    linkedin: shinichiro-imai-b4450290/
    # youtube: RickAstleyYT
    # tumblr: i-am-a-fish

google_analytics: "G-DGWQ6JZGY4"

disqus:
    shortname: Shin
